site_name: Time Teller
site_url: https://timeteller.arthurgassner.com
repo_url: https://github.com/arthurgassner/timeteller
repo_name: arthurgassner/timeteller
theme:
  name: material
  custom_dir: overrides # Needed for the google search metatag
  icon:
    logo: material/clock
    repo: fontawesome/brands/github
  favicon: assets/favicon.ico
  palette:
    scheme: slate  # Options: default, slate, or custom
    primary: red  # Primary color
    accent: white     # Accent color
plugins: [] # disable search
nav:
  - How to build it: index.md  
extra:
  analytics:
    provider: google
    property: G-GGE35FFPNQ
  social:
    - icon: fontawesome/solid/globe
      link: https://arthurgassner.com
    - icon: material/email
      link: mailto:arth.gassner@gmail.com
    - icon: fontawesome/brands/github 
      link: https://github.com/arthurgassner/timeteller-website
    - icon: fontawesome/brands/github 
      link: https://github.com/arthurgassner/timeteller
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes